### ISSUE TITLE
The tre value I calculated is different from yours

### ISSUE THREAD

**Issue by Zhenyu-040314** [vincentme/GroupRegNet#7]
Hi,Thanks for your sharing.
With your README.md of code, I could achieve the TRE result. But the result is quite different from yours，such as the dirlab case1,
the TRE I achieved is  1.89. I haven't changed your code， so I think there is a problem with my dataset. I tried to reprocess the dataset , but the results were incorrect.  I'm confused. 
Could you please provide the dataset you processed? Thank you very much!
Looking forward to your reply!

**Comment by vincentme** [comment]
Hi zhenyu,

For the dataset itself, I can not share since it belongs to dir-lab.com. But I can help you to figure out the reason for the deviation. It may be related to the indexing of the coordinates of the landmarks or the arrangement of the dimension of the image itself. 
> I assume the landmark array is in nx3 shape, last dim in x, y, z order. The origin is (0, 0, 0), e.g., 0-based indexing. The unit is voxel. 
> The image is in (D, H, W) or (z, y, x) shape

So you might need to open the landmark and image file, manually check to see if the landmark corresponds distinct feature in the image.

**Comment by Zhenyu-040314** [comment]
Thank you for your reply!

Very very grateful for your help!  Through your suggestion, I repreprocess the original data again.  I found that I didn't pay attention to the relationship between  landmarks coordinates and images  coordinates before. Now I can achieve the TRE result close to yours.  
Thank you very very much!
