### ISSUE TITLE
why use the "disp_t2i" instead of "disp_i2t"

### ISSUE THREAD

**Issue by NOTGOOOOD** [vincentme/GroupRegNet#8]
Hello,  I have seen your paper. It's great and I'm interested in this. Then I run your code, but the NCC is always -1.
In regnet.py  I find
`warped_input_image = self.spatial_transform(input_image, disp_t2i)`
I don't understand why use the "disp_t2i" that inversed  displacement filed to fed in STN.
Should I adjust something to this?

**Comment by vincentme** [comment]
Hi

Because here the objective is to warp the input image, which is the moving image, so the displacement should be from fixed image to moving image, e.g., template image to input image.

**Comment by Aflexiblebox** [comment]
Thank you for your response! But, I really don't know why the NCC is always -1 which trained on DIRLAB.

**Comment by Mobbyjj** [comment]
> Hi
> 
> Because here the objective is to warp the input image, which is the moving image, so the displacement should be from fixed image to moving image, e.g., template image to input image.

Hi, I implemented the code and found it confusing as well. The spatial tranformer should just transform the input_image to some others (i.e. template). So the code:
warped_input_image = self.spatial_transform(input_image, disp_t2i)
cannot do the task of transforming the template to the input images since it does not know what the template is. Could you point out what's wrong with my understanding?
